Repository TwoSSome/poompoom-web, pull requests merged in 2024-06, with the labels that each got.

#50 리뷰글 작성폼 GitHub Pages 배포
  .env
  .eslintrc.json
  package-lock.json
  package.json
  public/404.html
  public/index.html
  src/App.js
  src/components/Footer/Footer.styles.js
  src/components/Header/Header.container.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/PostDetail/PostDetail.container.js
  src/components/PostDetail/PostDetail.persenter.js
  src/components/SearchBar/SearchBar.container.js
  src/components/SearchBar/SearchBar.presenter.js
  src/components/SearchBar/SearchBar.styles.js
  src/index.js
  src/pages/QueryResult/QueryResultPage.js
  src/pages/Review/ReviewWritePage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.container.js
  src/pages/Review/components/PostFilter/PostFilter.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.styles.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.container.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.presenter.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.styles.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/ReviewWrite/ReviewWritePage.js
  src/shared/Theme.js
  yarn.lock
Labels: feature, deploy

#55 사용자 태그 입력창 UI
  src/pages/SignUp/component/SignUpTag/SignUpTag.js
  src/pages/SignUp/component/SignUpTag/component/Gender.js
  src/pages/SignUp/component/SignUpTag/component/Interest.js
  src/pages/SignUp/component/SignUpTag/component/Job.js
Labels: feature

#57 feat: 회원가입 페이지 라우팅 추가, 빠른 선물하기 review 컴포넌트로 이동
  src/App.js
  src/pages/QuickGift/QuickGift.js
  src/pages/QuickGift/QuickGiftPage.js
  src/pages/Review/components/QuickGift/QuickGift.js
  src/pages/Review/components/QuickGift/component/Age.js
  src/pages/Review/components/QuickGift/component/Image.js
  src/pages/Review/components/QuickGift/component/Interest.js
  src/pages/Review/components/QuickGift/component/Job.js
  src/pages/Review/components/QuickGift/component/Purpose.js
Labels: feature

#58 GitHub Pages URL redirect
  .env
  package.json
  public/index.html
  src/index.js
  yarn.lock
Labels: bug

#59 Bug: index.html PUBLIC URL 삭제 및 homepage 라우팅 수정
  public/index.html
Labels: bug

#61 로그인/회원가입 수정
  package-lock.json
  package.json
  src/apis/Success.js
  src/apis/authAxios.js
  src/apis/login.js
  src/apis/refresh.js
  src/pages/Login/LoginPage.js
  src/pages/Login/LoginSuccessPage.js
  src/pages/Login/components/Login.js
  src/pages/Login/components/LoginSuccess/LoginSuccess.js
  src/pages/Login/god.js
  src/pages/Login/index.js
  src/pages/Review/components/PostFilter/PostFilter.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/ReviewWrite/ReviewWritePage.js
  src/pages/SignUp/component/SignUp/SignUp.js
  yarn.lock
Labels: bug

#62 Homepage 수정
  src/App.js
  src/components/Footer/Footer.presenter.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/SearchBar/SearchBar.container.js
  src/components/SearchBar/SearchBar.presenter.js
  src/components/SearchBar/SearchBar.styles.js
  src/hooks/useRecommendations.js
  src/pages/Home/HomePage.js
  src/pages/LoverProfile/LoverProfilePage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
Labels: feature

#63 [FE] Author 프로필 폭죽 추가
  src/App.js
  src/assets/ALL_MOOD_VIEW.svg
  src/assets/FireCraker.svg
  src/assets/PoomPoom.svg
  src/assets/QUERY_VIEW.svg
  src/assets/RECENT_VIEW.svg
  src/assets/SUBSCRIBED_VIEW.svg
  src/components/AuthorComponent.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/LogoComponent.js
  src/index.js
  src/pages/Home/HomePage.js
  src/pages/QueryResult/QueryResultPage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.presenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestHeader/LatestHeader.container.js
  src/pages/Review/components/Section/LatestSection/LatestHeader/LatestHeader.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchHeader/SearchHeader.container.js
  src/pages/Review/components/Section/SearchSection/SearchHeader/SearchHeader.presenter.js
  src/pages/Review/components/Section/SubSection/SubHeader/SubHeader.container.js
  src/pages/Review/components/Section/SubSection/SubHeader/SubHeader.presenter.js
Labels: feature

#65 로그인 API 호출URL 수정
  src/App.js
  src/apis/refresh.js
  src/components/AuthorComponent.js
  src/index.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.presenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/SignUp/SignUpPage.js
  src/pages/SignUp/SignUpTagPage.js
  src/pages/SignUp/component/SignUp/SignUp.js
  src/pages/SignUp/component/SignUpTag/SignUpTag.js
Labels: feature

#66 Login 파일 경로 수정
  src/App.js
  src/components/AuthorComponent.js
  src/pages/QueryResult/QueryResultPage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
Labels: bug

#68 AT, RT 추가
  .eslintrc.json
  src/App.js
  src/apis/authAxios.js
  src/apis/authService.js
  src/apis/axios.js
  src/apis/refresh.js
  src/assets/FireCraker.svg
  src/assets/HorizontalCursor.svg
  src/assets/Main_1.svg
  src/components/AuthorComponent.js
  src/components/Footer/Footer.styles.js
  src/index.js
  src/pages/Home/HomePage.js
  src/pages/Join/Signup/Signup.style.js
  src/pages/Join/Signup/Signup.validation.js
  src/pages/Join/Signup/SignupPage.js
  src/pages/Join/SignupTag/SignupTagPage.js
  src/pages/Join/SignupTag/component/Gender.js
  src/pages/Join/SignupTag/component/Interest.js
  src/pages/Join/SignupTag/component/Job.js
  src/pages/Login/LoginPage.js
  src/pages/Login/LoginSuccessPage.js
  src/pages/Login/__god.js
  src/pages/Login/components/Login.js
  src/pages/Login/components/LoginSuccess/LoginSuccess.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.container.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.presenter.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.styles.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
  src/pages/SignUp/SignUpPage.js
  src/pages/SignUp/SignUpTagPage.js
Labels: feature

#69 fix: 충돌 해결
  src/App.js
  src/components/PostDetail/PostDetail.container.js
  src/components/PostDetail/PostDetail.persenter.js
  src/components/PostDetail/PostDetail.presenter.js
  src/pages/Join/SignupTag/SignupTagPage.js
  src/pages/LoverProfile/LoverProfileSetPage.js
  src/pages/Review/components/QuickGift/AgeSlider.js
  src/pages/Review/components/QuickGift/QuickGift.js
  src/pages/Review/components/QuickGift/SetQuickGift.js
Labels: bug

#70 feat: main page
  src/assets/4.svg
  src/assets/5.svg
  src/assets/6.svg
  src/assets/7.svg
  src/assets/Apple.svg
  src/assets/Chres.svg
  src/assets/D100.svg
  src/assets/Gift.svg
  src/assets/Group.svg
  src/assets/Main.svg
  src/assets/One.svg
  src/assets/Tre.svg
  src/assets/Two.svg
  src/assets/Vector.svg
  src/assets/calender.svg
  src/assets/lose.svg
  src/components/PostComment/PostCommentList/PostCommentList.js
  src/components/PostDetail/PostDetail.container.js
  src/components/PostDetail/PostDetail.presenter.js
  src/pages/Home/HomePage.js
Labels: feature

#71 리뷰글 페이지 무한 스크롤 구현
  src/App.js
  src/components/AuthorComponent.js
  src/components/Header/Header.container.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/PostDetail/PostDetail.container.js
  src/components/SearchBar/SearchBar.container.js
  src/components/SearchBar/SearchBar.presenter.js
  src/pages/Home/HomePage.js
  src/pages/QueryResult/QueryResultPage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.container.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.container.js
  src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.presenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.container.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.styles.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.container.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchHeader/SearchHeader.presenter.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.container.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.presenter.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
Labels: feature

#72 로그인 페이지 Protection 및 리다이렉션
  src/App.js
  src/ProtectedRoute.js
  src/assets/Footer.svg
  src/assets/Ranking4.svg
  src/components/Footer/Footer.presenter.js
  src/components/Footer/Footer.styles.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/pages/Home/HomePage.js
  src/pages/Login/LoginPage.js
  src/pages/LoverProfile/LoverProfileSetPage.js
  src/pages/Profile/components/ProfileBody/ProfileBody.presenter.js
  src/pages/Review/components/QuickGift/QuickGift.js
  src/pages/Review/components/QuickGift/SetQuickGift.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
Labels: feature

#75 최근 게시글 조회
  src/apis/authService.js
  src/apis/axios.js
  src/components/SearchBar/SearchBar.container.js
  src/pages/QueryResult/QueryResultPage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
Labels: feature

#77 feat: 댓글 작성, 보기 기능
  src/components/PostComment/PostCommentList/PostCommentList.container.js
  src/components/PostComment/PostCommentList/PostCommentList.presenter.js
  src/components/PostComment/PostCommentList/PostCommentList.styles.js
  src/components/PostComment/PostCommentWrite/PostCommentWrite.container.js
  src/components/PostDetail/PostDetail.presenter.js
  src/components/PostDetail/PostDetail.styles.js
  src/pages/Review/components/QuickGift/SetQuickGift.js
Labels: feature

#80 feat:빠른선물하기
  src/assets/Group 373.svg
  src/assets/Group 381.svg
  src/assets/Group 382.svg
  src/assets/Group22.svg
  src/assets/Mask group.svg
  src/assets/Union.svg
  src/assets/Vector (1).svg
  src/assets/Vector (2).svg
  src/components/PostComment/PostCommentList/PostCommentList.styles.js
  src/pages/LoverProfile/LoverProfilePage.js
  src/pages/LoverProfile/LoverProfileSetPage.js
  src/pages/Review/components/QuickGift/QuickGift.js
  src/pages/Review/components/QuickGift/QuickGifts/QuickGift.js
  src/pages/Review/components/QuickGift/QuickGifts/QuickGift.presenter.js
  src/pages/Review/components/QuickGift/QuickGifts/QuickGift.styles.js
  src/pages/Review/components/QuickGift/SetQuickGift/SetQuickGift.container.js
  src/pages/Review/components/QuickGift/SetQuickGift/setQuickGift.presenter.js
  src/pages/Review/components/QuickGift/SetQuickGift/setQuickGift.styles.js
Labels: feature

#82 모션 그래픽 추가
  package-lock.json
  package.json
  public/HorizontalCursor.cur
  public/HorizontalCursor.ico
  public/HorizontalCursor.png
  public/HorizontalCursor.svg
  public/index.html
  src/App.js
  src/animation/Particle1.json
  src/animation/Particle2.json
  src/animation/Particle3.json
  src/animation/PostWrite.json
  src/assets/DummyPhoto.svg
  src/assets/HorizontalCursor.cur
  src/assets/HorizontalCursor.png
  src/components/Header/Header.container.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/PostComment/PostCommentList/PostCommentList.styles.js
  src/fonts/OFL.txt
  src/fonts/Shrikhand-Regular.ttf
  src/fonts/TAEBAEK milkyway.ttf
  src/pages/Home/HomePage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/PostFilter/PostFilter.presenter.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.container.js
  src/pages/Review/components/Section/SubSection/SubAccount/SubAccount.presenter.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
  src/pages/ReviewWrite/ReviewWritePage.js
  src/style.css
  yarn.lock
Labels: feature
