Repository TwoSSome/poompoom-web, pull requests merged in 2024-05, with the labels that each got.

#15 리뷰글 페이지 컴포넌트 분리
  public/reset.css
  src/App.js
  src/components/PointModal/PointModal.js
  src/components/QuickGift/QuickGift.js
  src/components/RankingProfileCard/RankingProfileCard.js
  src/components/ReviewPost/ReviewPost.js
  src/components/ReviewPostBackground/ReviewPostBackground.js
  src/components/ReviewPostBody/ReviewPostBody.js
  src/components/ReviewPostHeader/ReviewPostHeader.js
  src/components/ReviewPostShortcut/ReviewPostShortcut.js
  src/pages/ReviewPage.js
  yarn.lock
Labels: feature

#17 feat:community 기본 기능 구현
  src/App.js
  src/components/Community/Comment/CommentList/CommentList.js
  src/components/Community/Comment/CommentWrite/CommentWrite.js
  src/components/Community/CommunityDetail/CommunityDetail.js
  src/components/Community/CommunityList/CommunityList.js
  src/components/Community/CommunityWrite/CommunityWrite.js
  src/pages/Community/Detail/CommunityDetailPage.js
  src/pages/Community/List/CommunityPage.js
  src/pages/Community/new/CommunityWritePage.js
  yarn.lock
Labels: feature

#25 폴더 구조 변경 및 공통 테마 설정
  package-lock.json
  package.json
  src/App.js
  src/components/Footer/Footer.container.js
  src/components/PointModal/PointModal.js
  src/components/PointModal/PointModal.presenter.js
  src/components/PointModal/PointModal.styles.js
  src/components/PostComment/PostCommentList/PostCommentList.presenter.js
  src/components/PostComment/PostCommentList/PostCommentList.styles.js
  src/components/PostComment/PostCommentWrite/PostCommentList.styles.js
  src/components/PostComment/PostCommentWrite/PostCommentWrite.presenter.js
  src/components/PostDetail/PostDetail.persenter.js
  src/components/PostDetail/PostDetail.styles.js
  src/components/PostSearch/PostSearch.presenter.js
  src/components/PostSearch/PostSearch.styles.js
  src/index.js
  src/pages/Home/HomePage.js
  src/pages/Profile/ProfilePage.js
  src/pages/Profile/components/ProfileBody/ProfileBody.js
  src/pages/Profile/components/ProfileBody/ProfileBody.presenter.js
  src/pages/Profile/components/ProfileBody/ProfileBody.styles.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.container.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.presenter.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.styles.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/QuickGift/QuickGift.js
  src/pages/Review/components/RankingProfileCard/RankingProfileCard.js
  src/pages/Review/components/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/RankingProfileCard/RankingProfileCard.styles.js
  src/pages/Review/components/ReviewPost/ReviewPost.js
  src/pages/Review/components/ReviewPost/ReviewPost.presenter.js
  src/pages/Review/components/ReviewPost/ReviewPost.styles.js
  src/pages/Review/components/ReviewPostBackground/ReviewPostBackground.js
  src/pages/Review/components/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/ReviewPostBackground/ReviewPostBackground.styles.js
  src/pages/Review/components/ReviewPostBody/ReviewPostBody.js
  src/pages/Review/components/ReviewPostBody/ReviewPostBody.presenter.js
  src/pages/Review/components/ReviewPostBody/ReviewPostBody.styles.js
  src/pages/Review/components/ReviewPostBox/ReviewPostBox.js
  src/pages/Review/components/ReviewPostBox/ReviewPostBox.presenter.js
  src/pages/Review/components/ReviewPostBox/ReviewPostBox.styles.js
  src/pages/Review/components/ReviewPostHeader/ReviewPostHeader.js
  src/pages/Review/components/ReviewPostHeader/ReviewPostHeader.presenter.js
  src/pages/Review/components/ReviewPostHeader/ReviewPostHeader.styles.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.presenter.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.styles.js
  src/shared/Theme.js
  yarn.lock
Labels: setting, feature

#28 fix: 모달창 css 변경
  src/App.js
  src/components/PointModal/PointModal.js
  src/components/PostDetail/PostDetail.js
  src/pages/Profile/components/ProfileBody/ProfileBody.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/ReviewPost/ReviewPost.js
Labels: bug

#29 랭킹 카드 추가 및 모달창 핫픽스 수정
  src/App.js
  src/App.styles.js
  src/components/PointModal/PointModal.container.js
  src/pages/Profile/ProfilePage.js
  src/pages/Profile/components/ProfileBody/ProfileBody.container.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.container.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.styles.js
  src/pages/Review/components/RankingProfileCard/RankingProfileCard.js
  src/pages/Review/components/ReviewContent/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/pages/Review/components/ReviewContent/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostAuthor/ReviewPostAuthor.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.container.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/ReviewContent/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostCard/ReviewPostCard.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostFilter/ReviewPostFilter.container.js
  src/pages/Review/components/ReviewContent/ReviewPostFilter/ReviewPostFilter.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostFilter/ReviewPostFilter.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.container.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostHashtags/ReviewPostHashtags.container.js
  src/pages/Review/components/ReviewContent/ReviewPostHashtags/ReviewPostHashtags.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostHashtags/ReviewPostHashtags.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.container.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.styles.js
  src/pages/Review/components/ReviewPost/ReviewPost.js
  src/pages/Review/components/ReviewPostBox/ReviewPostBox.presenter.js
  src/pages/Review/components/ReviewPostBox/ReviewPostBox.styles.js
  src/pages/Review/components/ReviewPostHeader/ReviewPostHeader.presenter.js
  src/pages/Review/components/ReviewPostHeader/ReviewPostHeader.styles.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.presenter.js
  src/pages/Review/components/ReviewPostShortcut/ReviewPostShortcut.styles.js
Labels: bug

#30 랭킹 애니매이션 구현
  package-lock.json
  package.json
  src/App.js
  src/components/Community/CommunityList/CommunityList.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.container.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.container.js
  yarn.lock
Labels: feature

#33 Feature/react css
  package-lock.json
  package.json
  src/App.js
  src/components/Header/Header.container.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/PostDetail/PostDetail.js
  src/components/PostDetail/PostDetail.presenter.js
  src/components/PostDetail/PostDetail.styles.js
  src/pages/Profile/ProfileEditPage.js
  src/pages/Profile/ProfilePage.js
  src/pages/Profile/components/ProfileBody/ProfileBody.container.js
  src/pages/Profile/components/ProfileBody/ProfileBody.presenter.js
  src/pages/Profile/components/ProfileBody/ProfileBody.styles.js
  src/pages/Profile/components/ProfileEdit/ProfileEdit.container.js
  src/pages/Profile/components/ProfileEdit/ProfileEdit.presenter.js
  src/pages/Profile/components/ProfileEdit/ProfileEdit.styles.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.container.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.presenter.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.styles.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.container.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.presenter.js
  src/pages/Profile/components/ProfileMenuBox/ProfileMenuBox.styles.js
  src/pages/Review/ReviewWritePage.js
  src/pages/Review/components/ReviewContent/ReviewConfetti/ReviewConfetti.container.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.container.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostBackground/ReviewPostBackground.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/ReviewContent/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostFilter/ReviewPostFilter.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostFilter/ReviewPostFilter.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostGallery/ReviewPostGallery.styles.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.container.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/ReviewContent/ReviewPostPreview/ReviewPostPreview.styles.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.container.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.presenter.js
  src/pages/Review/components/ReviewWrite/ReviewWrite.styles.js
  yarn.lock
Labels: feature

#36 폴더 경로 수정
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
Labels: invalid

#37 리뷰글 박스 사이즈 조절 및 레이아웃 수정
  src/components/PostDetail/PostDetail.container.js
  src/components/PostDetail/PostDetail.persenter.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.container.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.presenter.js
  src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.styles.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
  src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
  src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.presenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.container.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.styles.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
Labels: feature

#40 리뷰 자세히보기 라우팅 연결
  src/App.js
  src/components/Header/Header.styles.js
  src/components/PostDetail/PostDetail.container.js
  src/components/PostDetail/PostDetail.persenter.js
  src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
  src/pages/Review/components/Ranking/Card/Card.conatiner.js
  src/pages/Review/components/Ranking/Card/Card.presenter.js
  src/pages/Review/components/Ranking/Card/Card.styles.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.container.js
  src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
Labels: feature

#45 feat: react-hook-form & yup으로 회원가입 폼 작성
  package-lock.json
  package.json
  src/App.js
  src/pages/Login/LoginPage.js
  src/pages/Login/SignUpPage.js
  src/pages/Login/components/SignUp/SignUp.js
  src/pages/Login/components/SignUp/SignUp.style.js
  src/pages/Login/components/SignUp/SignUp.validation.js
  yarn.lock
Labels: feature

#47 feat: Login/SignUp 구현
  src/App.js
  src/apis/Success.js
  src/apis/authAxios.js
  src/apis/login.js
  src/apis/refresh.js
  src/pages/Login/components/Login.js
  src/pages/Login/components/LoginSuccess/LoginSuccess.js
  src/pages/Profile/components/ProfileBody/ProfileBody.container.js
  src/pages/SignUp/SignUpPage.js
  src/pages/SignUp/component/SignUp/SignUp.js
  src/pages/SignUp/component/SignUp/SignUp.style.js
  src/pages/SignUp/component/SignUp/SignUp.validation.js
  src/stores/index.js
  yarn.lock
Labels: feature
