Repository TwoSSome/poompoom-web, pull requests merged in 2024-11, with the labels that each got.

#121 fix: 리뷰 작성 및 상세페이지 링크, 품목 추가, 디자인 개선, 연인 연동 페이지 라우팅 개선
  package.json
  src/App.js
  src/assets/LinkImg.svg
  src/assets/Lottie-Animation/checkAnimation.json
  src/components/Comment/CommentContainer.js
  src/components/Comment/CommentEmpty.js
  src/components/Comment/CommentWrite.js
  src/components/Comment/subComponents/EditComment.js
  src/components/Community/CommunityList/CommunityList.js
  src/components/common/DropDownOption.js
  src/hooks/useQuestion.js
  src/pages/LoverSet/Connect/Connect.js
  src/pages/LoverSet/ConnectGuidePage.js
  src/pages/LoverSet/Recommend/Recommend.js
  src/pages/LoverSet/Recommend/Recommend.style.js
  src/pages/LoverSet/SetRecommendPage.js
  src/pages/LoverSet/SetValuePage.js
  src/pages/LoverSet/components/SetConstant.js
  src/pages/LoverSet/components/SetQuestion.js
  src/pages/LoverSet/style.js
  src/pages/Review/ReviewCreate/ReviewCreate.presenter.js
  src/pages/Review/ReviewCreate/ReviewCreate.style.js
  src/pages/Review/ReviewCreate/ReviewCreatePage.js
  src/pages/Review/ReviewCreatePage.js
  src/pages/Review/ReviewEdit.style.js
  src/pages/Review/ReviewEditPage.js
  src/pages/ReviewDetail/PostComment/PostCommentWrite/PostCommentWrite.container.js
  src/pages/ReviewDetail/PostDetail/PostDetail.container.js
  src/pages/ReviewDetail/PostDetail/PostDetail.presenter.js
  src/pages/ReviewDetail/PostDetail/PostDetail.styles.js
  src/pages/ReviewDetail/ReviewDetailPage.js
  src/pages/index.js
  src/shared/item.js
  yarn.lock
Labels: enhancement, design, feature

#123 fix: api오류 수정, 디자인, 라우터, 로딩 추가
  src/ProtectedRoute.js
  src/assets/Lottie-Animation/presentLoading.json
  src/components/Category/Category.js
  src/components/Loading.js
  src/components/PostFilter/PostFilter.presenter.js
  src/hooks/CommentApis/useComment.js
  src/pages/LoverSet/ConnectGuidePage.js
  src/pages/OAuth/SignUpSocial.js
  src/pages/Profile/ProfilePage.js
  src/pages/Review/ReviewEditPage.js
  src/pages/ReviewDetail/PostDetail/PostDetail.container.js
  src/pages/ReviewDetail/PostDetail/PostDetail.presenter.js
Labels: enhancement, design

#124 feature: 검색바 추천 기능 구현
  .env
  .eslintrc.json
  package-lock.json
  package.json
  src/App.js
  src/apis/authService.js
  src/assets/filter.svg
  src/assets/poompoom_new.svg
  src/assets/ranking_on_off.svg
  src/assets/search_keyword.svg
  src/components/Header/Header.container.js
  src/components/PostFilter/PostFilter.container.js
  src/components/ReviewPostCard/ReviewPostAuthor/ReviewPostAuthor.container.js
  src/components/ReviewPostCard/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/components/ReviewPostCard/ReviewPostCard.presenter.js
  src/components/SearchBar/AutoCompleteKeywords.js
  src/components/SearchBar/Recommendations.js
  src/components/SearchBar/SearchBar.container.js
  src/components/SearchBar/SearchBar.presenter.js
  src/components/SearchBar/SearchBar.styles.js
  src/components/common/FollowBtutton.js
  src/constants/SubscriptionInitialState.js
  src/hooks/useDebounce.js
  src/hooks/useFetchAllHashtags.js
  src/hooks/useFetchProfilePicture.js
  src/hooks/useFetchRecommendations.js
  src/hooks/useInfiniteScroll.js
  src/index.js
  src/pages/Home/HomePage.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.presenter.js
  src/pages/Profile/components/Section/LatestProfileGallery/LatestProfileGallery.presenter.js
  src/pages/Profile/components/Section/MineProfileGallery/MineProfileGallery.presenter.js
  src/pages/Query/QueryPage.js
  src/pages/Query/components/NotFound.js
  src/pages/Review/ReviewCreate/ReviewCreate.presenter.js
  src/pages/Review/ReviewCreate/ReviewCreatePage.js
  src/pages/Review/ReviewEditPage.js
  src/pages/Review/ReviewPage.js
  src/pages/Review/components/Section/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/LatestGallery/LatestGallery.presenter.js
  src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
  src/pages/Review/components/Section/SearchGallery/SearchGallery.container.js
  src/pages/Review/components/Section/SearchGallery/SearchGallery.presenter.js
  src/pages/Review/components/Section/SubAccount/SubAccount.container.js
  src/pages/Review/components/Section/SubAccount/SubAccount.presenter.js
  src/pages/Review/components/Section/SubGallery/SubGallery.container.js
  src/pages/Review/components/Section/SubGallery/SubGallery.presenter.js
  src/pages/ReviewDetail/PostDetail/PostDetail.container.js
  src/pages/ReviewDetail/PostDetail/PostDetail.presenter.js
  src/pages/index.js
  src/recoil/InitializeNickname.js
  src/recoil/atoms.js
  src/recoil/axiosState.js
  src/recoil/recommendationsState.js
  yarn.lock
Labels: bug, enhancement, feature

#125 fix: 검색 자동 추천 기능 수정
  src/hooks/useFetchFailKeyword.js
  src/hooks/useRecommendations.js
  src/pages/Query/QueryPage.js
  src/pages/Query/components/NotFound.js
  src/pages/Review/components/Section/SubAccount/SubAccount.container.js
Labels: enhancement, feature

#126 프로필 태그 및 url 수정
  src/App.js
  src/assets/BookMark/Category.svg
  src/assets/BookMark/Folder.svg
  src/components/Category/Category.js
  src/components/Comment/CommentContainer.js
  src/components/Comment/CommentList.js
  src/components/Comment/subComponents/PinComment.js
  src/components/Header/Header.presenter.js
  src/components/Header/Header.styles.js
  src/components/ProfileTag/AgeSlider.js
  src/components/ProfileTag/Gender.js
  src/components/ProfileTag/Interest.js
  src/components/ProfileTag/Job.js
  src/components/ReviewPostCard/ReviewPostAuthor/ReviewPostAuthor.presenter.js
  src/hooks/CommentApis/useComment.js
  src/hooks/CommentApis/useDeleteComment.js
  src/pages/Join/SignupTag/SignUpTag.presenter.js
  src/pages/Join/SignupTag/SignUpTag.styles.js
  src/pages/Profile/ProfilePage.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.container.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.presenter.js
  src/pages/Profile/components/ProfileHeader/ProfileHeader.styles.js
  src/pages/Profile/components/Section/Category/Category.js
  src/pages/Review/ReviewCreate/ReviewCreate.presenter.js
  src/pages/Review/ReviewCreate/ReviewCreate.style.js
  src/pages/Review/ReviewCreate/ReviewCreatePage.js
  src/pages/Review/ReviewEditPage.js
  src/pages/ReviewDetail/PostDetail/PostDetail.presenter.js
  src/pages/ReviewDetail/PostDetail/PostDetail.styles.js
Labels: bug
