Repository TwoSSome/poompoom-web, pull requests merged in 2025-01, with the labels that each got.

#127 refactor: App 레이아웃 route 관리
  src/App.js
  src/components/Header/Header.presenter.js
  src/constants/initialProfile.js
  src/hooks/useFetchAllHashtag.js
  src/layouts/HeaderOnlyLayout.js
  src/layouts/MainLayout.js
  src/layouts/NoLayout.js
  src/pages/Community/Detail/CommunityDetailPage.js
  src/pages/Community/List/CommunityPage.js
  src/pages/Community/New/CommunityWritePage.js
  src/pages/LoversProfile/QuickGift/SetQuickGift.js
  src/pages/LoversProfile/QuickGift/SetQuickGift/SetQuickGift.container.js
  src/pages/LoversProfile/QuickGift/SetQuickGift/setQuickGift.presenter.js
  src/routes/AppRoutes.js
  src/routes/ProtectedRoute.js
  src/services/profile/getMyProfile.js
Labels: enhancement

#128 feat: 나머지 레이아웃 수정 코드
  src/App.js
  src/hooks/useScrollToTop.js
  src/layouts/HeaderOnlyLayout.js
  src/layouts/Layout.styles.js
  src/layouts/MainLayout.js
  src/layouts/NoLayout.js
Labels: enhancement

#129 feat: 캘린더 프레임 제작 및 회원가입 중복체크 로직 추가
  src/pages/Calendar/CalendarPage.js
  src/pages/Calendar/components/CalendarView/CalendarView.js
  src/pages/Calendar/components/Sidebar/Sidebar.js
  src/pages/Join/Signup/SignupPage.js
  src/pages/index.js
  src/routes/AppRoutes.js
Labels: feature

#130 feat: calendar view 프로토타입 구현
  src/pages/Calendar/CalendarPage.js
  src/pages/Calendar/components/CalendarView/CalendarView.js
  src/pages/Calendar/components/CalendarView/EventDetailModal.js
  src/pages/Calendar/components/CalendarView/EventModal.js
  src/pages/Calendar/components/CalendarView/PostDetailModal.js
  src/pages/Calendar/components/CalendarView/PostModal.js
  src/pages/index.js
  src/routes/AppRoutes.js
Labels: feature

#131 feat: sidebar 프로토타입 구현
  .vscode/settings.json
  package.json
  src/assets/Calender/Sidebar/addImage.svg
  src/assets/Calender/Sidebar/blueMoon.svg
  src/assets/Calender/Sidebar/calenderCount.svg
  src/assets/Calender/Sidebar/calenderHeart.svg
  src/assets/Calender/Sidebar/emptyCalenderProfile.svg
  src/assets/Calender/Sidebar/icedGelly.svg
  src/assets/Calender/Sidebar/poompoom.svg
  src/assets/Calender/Sidebar/sexyCool.svg
  src/assets/Calender/Sidebar/sweetHerb.svg
  src/assets/Calender/Sidebar/url.svg
  src/assets/Calender/Sidebar/warmVivid.svg
  src/components/Header/Header.presenter.js
  src/pages/Calendar/CalendarPage.js
  src/pages/Calendar/components/Modal/DatePlanModal.js
  src/pages/Calendar/components/Sidebar/Section/AddDatePlan.js
  src/pages/Calendar/components/Sidebar/Section/Alarm.js
  src/pages/Calendar/components/Sidebar/Section/Counter.js
  src/pages/Calendar/components/Sidebar/Section/DatePlan.js
  src/pages/Calendar/components/Sidebar/Section/ImportPlan.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoomLog.js
  src/pages/Calendar/components/Sidebar/Section/Search.js
  src/pages/Calendar/components/Sidebar/Section/Theme.js
  src/pages/Calendar/components/Sidebar/Sidebar.js
  src/pages/Calendar/components/Sidebar/Style.js
  yarn.lock
Labels: feature

#132 feat: poom poom log에 게시글 및 일정 연동
  src/pages/Calendar/CalendarPage.js
  src/pages/Calendar/components/CalendarView/CalendarView.js
  src/pages/Calendar/components/CalendarView/EventModal.js
  src/pages/Calendar/components/CalendarView/PostDetailModal.js
  src/pages/Calendar/components/CalendarView/PostModal.js
  src/pages/Calendar/components/Sidebar/Section/Counter.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoom.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoom.styled.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoomLog.js
  src/pages/Calendar/components/Sidebar/Sidebar.js
Labels: feature

#134 feat: 게시글 날짜 선택 창 추가
  src/pages/Calendar/components/CalendarView/PostModal.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoom.js
Labels: feature

#135 feat: 카테고리에 따른 일정 입력 데이터 변경
  src/pages/Calendar/components/CalendarView/CalendarView.js
  src/pages/Calendar/components/CalendarView/EventCreateModal.js
  src/pages/Calendar/components/CalendarView/EventDetailModal.js
  src/pages/Calendar/components/CalendarView/PostCreateModal.js
  src/pages/Calendar/components/CalendarView/PostDetailModal.js
Labels: bug, enhancement, feature

#136 feat: 회고록/계획글 분리 및 사이드바 기능 추가
  .vscode/settings.json
  src/pages/Calendar/CalendarPage.js
  src/pages/Calendar/components/CalendarView/CalendarView.js
  src/pages/Calendar/components/CalendarView/EventCreateModal.js
  src/pages/Calendar/components/CalendarView/EventDetailModal.js
  src/pages/Calendar/components/CalendarView/LogCreateModal.js
  src/pages/Calendar/components/CalendarView/LogDetailModal.js
  src/pages/Calendar/components/CalendarView/PostCreateModal.js
  src/pages/Calendar/components/Sidebar/Section/Alarm.js
  src/pages/Calendar/components/Sidebar/Section/Counter.js
  src/pages/Calendar/components/Sidebar/Section/DatePlan.js
  src/pages/Calendar/components/Sidebar/Section/Event.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoom.js
  src/pages/Calendar/components/Sidebar/Section/PoomPoom.styled.js
  src/pages/Calendar/components/Sidebar/Sidebar.js
  src/pages/Calendar/components/Sidebar/Style.js
  src/pages/Lover/LoverPage.js
  src/pages/LoverSet/ConnectGuidePage.js
  src/pages/Mating/Mating.Styled.js
  src/pages/Mating/Mating.js
  src/pages/index.js
  src/routes/AppRoutes.js
Labels: feature
